---
title: "NEON AOP maps"
author: "Kelly Hondula"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
library(sf)
library(mapview)
library(leaflet)
```

## Data

Set up folder for data

```{r}
data_dir <- "data"
if(!fs::dir_exists(data_dir)){
  fs::dir_create(data_dir)
}
```

Download kmz from neon website

```{r}
aop_kmz_filepath <- "https://www.neonscience.org/aop-flight-boundaries-kmz"
aop_kmz_localfile <- glue::glue("{data_dir}/aop-flight-boundaries.kmz")
download.file(aop_kmz_filepath, destfile = aop_kmz_localfile)
```

```{r}
aop_sf <- sf::st_read(aop_kmz_localfile) %>% 
  st_zm() %>% mutate(sitecode = substr(Name, 1, 8),
                     domain = substr(Name, 1, 3))
aop_centroids_sf <- aop_sf %>% 
  st_centroid(aop_sf, of_largest_polygon = TRUE)
```

How many sites? 

```{r}
sitecodes <- unique(aop_sf$sitecode)
length(sitecodes)
```

Leaflet map of sites

```{r}
aop_sf %>%
  leaflet() %>%
  addTiles(group = "Open Street Map") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri World Imagery") %>%
  addPolygons(popup = ~Name) %>%
  addLayersControl(baseGroups = c("Esri World Imagery", "Open Street Map"),
                   options = layersControlOptions(collapsed = FALSE))
```

```{r}
site_bbox <- aop_sf %>%
  filter(sitecode == "D01_HARV") %>%
  st_bbox()

aop_sf %>%
  filter(sitecode == "D01_HARV") %>%
  leaflet() %>%
  fitBounds(lng1 = site_bbox[["xmin"]],
            lng2 = site_bbox[["xmax"]],
            lat1 = site_bbox[["ymin"]],
            lat2 = site_bbox[["ymax"]]) %>%
  addTiles(group = "Open Street Map") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri World Imagery") %>%
  addPolygons(popup = ~Name, fillOpacity = 0, opacity = 1,
              weight = 10, color = "yellow") %>%
  addLayersControl(baseGroups = c("Esri World Imagery", "Open Street Map"),
                   options = layersControlOptions(collapsed = FALSE))
```

# Save PDF of a flightbox

Define a function to save an image for a given site

```{r}
save_bigmap <- function(my_sitename, my_vwidth = 12000, my_vheight = 8000){

  site_bbox <- aop_sf %>%
  filter(sitecode == my_sitename) %>%
  st_bbox()

  mp <- aop_sf %>%
    filter(sitecode == my_sitename) %>%
    leaflet() %>%
    fitBounds(lng1 = site_bbox[["xmin"]],
            lng2 = site_bbox[["xmax"]],
            lat1 = site_bbox[["ymin"]],
            lat2 = site_bbox[["ymax"]]) %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri World Imagery") %>%
  addPolygons(popup = ~Name, fillOpacity = 0, opacity = 1,
              weight = 10, color = "yellow") 
  
  
  mapshot(mp, 
          file = glue::glue("map_site-{my_sitename}.pdf"), 
          vwidth = my_vwidth, vheight = my_vheight)
}

```

Use function

```{r, eval = FALSE}
# one at a time
save_bigmap(my_sitename = "D01_HARV")
# over all sites
purrr::walk(sitecodes, ~save_bigmap(.x))
```

